---
- name: Baixando Docker CE
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'
- name: Instalando Docker CE
  shell: /tmp/get-docker.sh
- name: Limpando Arquivos Temporários do Docker CE
  file:
    state: absent
    path: /tmp/get-docker.sh
