---
- name: Atualizando e inserindo todos repositórios e pacotes
  apt:
    update_cache: yes
    cache_valid_time: 3600
    upgrade: dist
    force_apt_get: yes
- name: Instalando Python3 e Pip3
  apt:
    update_cache: yes
    pkg:
      - python
      - python-pip
      - python-dev
      - python3
      - python3-pip
      - python3-dev
- name: Instalando Git e Curl
  apt:
    update_cache: yes
    pkg:
      - git
      - curl
- name: Instalando Docker-py
  pip:
    name: docker-py
    state: present
